name: study_bank
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.4.0
  cupertino_icons: ^1.0.2
  easy_separator: ^1.0.1
  firebase_auth: ^4.2.8
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_zoom_drawer: ^2.1.2
  font_awesome: ^5.10.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^6.1.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/DB/papers/
    - assets/icons/
    - assets/storage_files/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
