// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDoDo_LofKfOuxwszda9JJKEzlfMQNvD-U',
    appId: '1:611285769883:web:2f2c74928096e51987303e',
    messagingSenderId: '611285769883',
    projectId: 'studybank-873e8',
    authDomain: 'studybank-873e8.firebaseapp.com',
    storageBucket: 'studybank-873e8.appspot.com',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyDh_Gsl21CMfo1PvaAucatpbl-HgPawxR0',
    appId: '1:611285769883:android:63fab05f6ee2a42c87303e',
    messagingSenderId: '611285769883',
    projectId: 'studybank-873e8',
    storageBucket: 'studybank-873e8.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyAwqn0tSina-Bhel5Dkzj_HTwcke-VmJWo',
    appId: '1:611285769883:ios:46a505ffdb938d2d87303e',
    messagingSenderId: '611285769883',
    projectId: 'studybank-873e8',
    storageBucket: 'studybank-873e8.appspot.com',
    iosClientId:
        '611285769883-221lhpvr63pp9llnksfeeaeidkfkcq0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyBank',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyAwqn0tSina-Bhel5Dkzj_HTwcke-VmJWo',
    appId: '1:611285769883:ios:46a505ffdb938d2d87303e',
    messagingSenderId: '611285769883',
    projectId: 'studybank-873e8',
    storageBucket: 'studybank-873e8.appspot.com',
    iosClientId:
        '611285769883-221lhpvr63pp9llnksfeeaeidkfkcq0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyBank',
  );
}
